using System.Collections.Generic;
using UnityEngine;

namespace ProceduralGeneration
{
    public enum FlightPreviewMode
    {
        /// <summary>LOD falls off with distance to <see cref="TerrainDataConfig.center"/>.</summary>
        Radius,
        /// <summary>LOD falls off with distance to <see cref="TerrainDataConfig.path"/>.</summary>
        Path,
    }
    public enum DownloadMode
    {
        Single,
        Area
    }

    /// <summary>
    /// Every SAT tile that has to be loaded, as Web Mercator XYZ tiles (used to retrieve the ArcGIS tiles),
    /// together with the settings they were generated from in the Flight Preview window.
    /// </summary>
    [CreateAssetMenu(menuName = "Procedural Generation/Terrain Data Config")]
    public class TerrainDataConfig : ScriptableObject
    {
        [Header("Generation")]
        public FlightPreviewMode mode = FlightPreviewMode.Radius;
        public TileLodSettings lodSettings = TileLodSettings.Default;

        [Tooltip("Radius mode focus, mercator (EPSG:3857, metres).")]
        public DoubleVector2 center;

        [Tooltip("Path mode flight path nodes, mercator (EPSG:3857, metres).")]
        public List<DoubleVector2> path = new List<DoubleVector2>();

        [Header("Tiles")]
        [Tooltip("Tiles to load, coarse zoom first. Generated by Tools/Procedural Generation/Flight Preview.")]
        public List<TileBounds> tiles = new List<TileBounds>();

        [Header("Download properties")]
        public DownloadMode downloadMode;
        public string downloadDstFolder;
        public TileBounds tileToDownload;
        public int colorZoom;
        public int heightZoom;

        public ILodFocus CreateFocus() => mode == FlightPreviewMode.Path
            ? new PathLodFocus(path)
            : new PointLodFocus(center);

        public TileLodBuilder.Result Generate() => TileLodBuilder.Build(lodSettings, CreateFocus());

        private void OnValidate()
        {
            lodSettings.Validate();
        }

        /// <summary>
        /// Blue for <paramref name="minZoom"/> to red for <paramref name="maxZoom"/>.
        /// </summary>
        public static Color GetZoomColor(int zoom, int minZoom, int maxZoom)
        {
            float t = maxZoom > minZoom ? Mathf.InverseLerp(minZoom, maxZoom, zoom) : 1;
            return Color.HSVToRGB(Mathf.Lerp(0.62f, 0f, t), 0.85f, 1f);
        }
    }
}
